name: Deploy Site
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Get system info
      - run: ifconfig
      - run: sudo dmidecode
      - run: df -h
      - run: free -m
      - run: echo "GitHub branch is ${{ github.ref }}"

      # Install Hugo
      # Download latest version of Hugo
      - run: |
          latest=$(curl --silent "https://api.github.com/repos/gohugoio/hugo/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/' | cut -c2-)
          wget https://github.com/gohugoio/hugo/releases/download/v${latest}/hugo_extended_${latest}_Linux-64bit.deb -O hugo.deb
          sudo dpkg -i hugo.deb

      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your workflow can access it
      - name: Checkout repo
        uses: actions/checkout@master

      # Build Hugo Site
      - run: echo "Building hugo site"
      - run: hugo

      - name: Publish to Distributed Press
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: hyphacoop/actions-distributed-press@v1.1.0
        with:
          publish_dir: ./public
          dp_url: https://srv2.distributed.press
          refresh_token: ${{ secrets.DISTRIBUTED_PRESS_API_KEY }}
          site_url: two.compost.digital
