name: Deploy Site
on:
  push:
    branches:
      - master
      - v1-prod
  pull_request:
    branches:
      - master
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Get system info
      - run: ifconfig
      - run: sudo dmidecode
      - run: df -h
      - run: free -m
      - run: echo "GitHub branch is ${{ github.ref }}"

      # Install Hugo
      # Download latest version of Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.89.4'
          extended: true

      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your workflow can access it
      - name: Checkout repo
        uses: actions/checkout@master

      # Build Hugo Site
      - run: echo "Building hugo site"
      - run: hugo

      - name: Publish to Distributed Press
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: hyphacoop/actions-distributed-press@v1.1.0
        with:
          publish_dir: ./public
          dp_url: https://api.distributed.press
          refresh_token: ${{ secrets.DISTRIBUTED_PRESS_API_KEY }}
          site_url: two.compost.digital
